id: https://example.com/VIRUSMVP
name: VIRUSMVP_SARS-CoV-2
description: ''
version: 1.0.0
in_language:
- en
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  dcterms: http://purl.org/dc/terms/
  GENEPIO: http://purl.obolibrary.org/obo/GENEPIO_
  NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
  OBI: http://purl.obolibrary.org/obo/OBI_
  SIO: http://semanticscience.org/resource/SIO_
classes:
  dh_interface:
    name: dh_interface
    description: A DataHarmonizer interface
  VIRUSMVP_SARS-CoV-2:
    name: VIRUSMVP_SARS-CoV-2
    description: Specification for VIRUS-MVP SARS-CoV-2 mutation functional impact
      data gathering
    is_a: dh_interface
    see_also: templates/virusmvp/SOP.pdf
    slots:
    - organism
    - reference_accession
    - reference_database_name
    - nucleotide_position
    - original_mutation_description
    - nucleotide_mutation
    - amino_acid_mutation
    - amino_acid_mutation_alias
    - gene_name
    - gene_symbol
    - protein_name
    - protein_symbol
    - variant_functional_effect
    - variant_functional_effect_description
    - author
    - publication_year
    - URL
    - DOI
    - PMID
    - peer_review_status
    - curator
    - mutation_functional_annotation_resource
    slot_usage:
      organism:
        rank: 1
        slot_group: reference sequence information
      reference_accession:
        rank: 2
        slot_group: reference sequence information
      reference_database_name:
        rank: 3
        slot_group: reference sequence information
      nucleotide_position:
        rank: 4
        slot_group: mutation location information
      original_mutation_description:
        rank: 5
        slot_group: mutation location information
      nucleotide_mutation:
        rank: 6
        slot_group: mutation location information
      amino_acid_mutation:
        rank: 7
        slot_group: mutation location information
      amino_acid_mutation_alias:
        rank: 8
        slot_group: mutation location information
      gene_name:
        rank: 9
        slot_group: mutation location information
      gene_symbol:
        rank: 10
        slot_group: mutation location information
      protein_name:
        rank: 11
        slot_group: mutation location information
      protein_symbol:
        rank: 12
        slot_group: mutation location information
      variant_functional_effect:
        rank: 13
        slot_group: functional effect information
      variant_functional_effect_description:
        rank: 14
        slot_group: functional effect information
      author:
        rank: 15
        slot_group: literature citation
      publication_year:
        rank: 16
        slot_group: literature citation
      URL:
        rank: 17
        slot_group: literature citation
      DOI:
        rank: 18
        slot_group: literature citation
      PMID:
        rank: 19
        slot_group: literature citation
      peer_review_status:
        rank: 20
        slot_group: literature citation
      curator:
        rank: 21
        slot_group: contributor acknowledgement
      mutation_functional_annotation_resource:
        rank: 22
        slot_group: contributor acknowledgement
slots:
  organism:
    name: organism
    title: organism
    description: The virus being analyzed.
    slot_uri: OBI:0100026
    range: organism menu
    required: true
    examples:
    - value: Severe acute respiratory syndrome coronavirus 2
  reference_accession:
    name: reference_accession
    title: reference accession
    description: An identifier that specifies an individual sequence record in a public
      sequence repository.
    comments: Use the versioned accession number here.
    slot_uri: OBI:0002885
    range: reference accession menu
    required: true
    examples:
    - value: NC_045512.2
  reference_database_name:
    name: reference_database_name
    title: reference database name
    description: An identifier of a biological or bioinformatics database.
    comments: The name of the reference database may need to be entered manually if
      not automatically recorded as a parameter within the tool.
    slot_uri: OBI:0002883
    range: reference database menu
    required: true
    examples:
    - value: RefSeq
  nucleotide_position:
    name: nucleotide_position
    title: nucleotide position
    description: A sequence datum which is the 1-based start position of a sequence
      feature for a given nucleotide sequence.
    slot_uri: GENEPIO:0101033
    range: integer
    minimum_value: 0
    required: true
    examples:
    - value: '351'
  original_mutation_description:
    name: original_mutation_description
    title: original mutation description
    description: A sequence datum which describes a mutation, written in the user's
      own notation.
    slot_uri: GENEPIO:0101030
    range: string
    required: true
    examples:
    - value: D614G, 12-bp deletion in E at nucleotide position 54647, D to G substitution
        at amino acid 614
  nucleotide_mutation:
    name: nucleotide_mutation
    title: nucleotide mutation
    description: A sequence datum which describes a nucleotide sequence change as
      compared to a reference sequence, represented by a specified notation system.
    comments: Use HGVS syntax; c. (coding) g.(genomic), or r. (ribosomal) mutations
      should be included here.
    slot_uri: GENEPIO:0100402
    range: WhitespaceMinimizedString
    recommended: true
    examples:
    - value: NC_045512.2:c.1850_1851insGT
  amino_acid_mutation:
    name: amino_acid_mutation
    title: amino acid mutation
    description: A sequence datum which describes an amino acid sequence change as
      compared to a reference sequence, represented by a specified notation system.
    comments: Use HGVS syntax; p. (protein) mutations should be included here; use
      3 letter code preferred for amino acids. For multiple amino acids that are correlated
      with a functional impact as a group, input a comma-separated list of mutations.
      It does not need to be known whether all mutations in the group are individually
      correlated with the functional impact.
    slot_uri: GENEPIO:0100406
    range: WhitespaceMinimizedString
    required: true
    examples:
    - value: YP_009724390.1:p.Cys3563Ser, YP_009724390.1:p.Asp614Gly
  amino_acid_mutation_alias:
    name: amino_acid_mutation_alias
    title: amino acid mutation alias
    description: For SARS-CoV-2. The alias is an amino acid name indexed from the
      start of each nsp in Orf1ab, as opposed to from the start of the gene as is
      the default.
    comments: Use HGVS syntax; p. (protein) mutations should be included here; use
      3 letter code preferred for amino acids.
    slot_uri: GENEPIO:0100406
    range: WhitespaceMinimizedString
    examples:
    - value: YP_009724390.1:p.Cys300Ser
  gene_name:
    name: gene_name
    title: gene name
    description: The name of a gene, (typically) assigned by a person and/or according
      to a naming scheme. It may contain white space characters and is typically more
      intuitive and readable than a gene symbol. It (typically) may be used to identify
      similar genes in different species and to derive a gene symbol.
    slot_uri: GENEPIO:0101130
    range: gene name menu
    required: true
    examples:
    - value: surface glycoprotein gene (SARS-CoV-2)
  gene_symbol:
    name: gene_symbol
    title: gene symbol
    description: The short name of a gene; a single word that does not contain white
      space characters. It is typically derived from the gene name.
    slot_uri: GENEPIO:0101131
    range: gene symbol menu
    required: true
    examples:
    - value: s gene (SARS-CoV-2)
  protein_name:
    name: protein_name
    title: protein name
    description: The name of a protein, (typically) assigned by a person and/or according
      to a naming scheme. It may contain white space characters and is typically more
      intuitive and readable than a protein symbol. It (typically) may be used to
      identify similar proteins in different species and to derive a protein symbol.
    slot_uri: GENEPIO:0101132
    range: protein name menu
    required: true
    examples:
    - value: surface glycoprotein (SARS-CoV-2)
  protein_symbol:
    name: protein_symbol
    title: protein symbol
    description: The short name of a protein; a single word that does not contain
      white space characters. It is typically derived from the protein name.
    slot_uri: GENEPIO:0101133
    range: protein symbol menu
    required: true
    examples:
    - value: S protein (SARS-CoV-2)
  variant_functional_effect:
    name: variant_functional_effect
    title: variant functional effect
    description: The functional category of the mutation impact.
    comments: Freetext; a future update will have a picklist here.
    slot_uri: GENEPIO:0101127
    range: string
    required: true
    examples:
    - value: dimerization
  variant_functional_effect_description:
    name: variant_functional_effect_description
    title: variant functional effect description
    description: A freetext description of the functional effect of a mutation.
    slot_uri: GENEPIO:0101036
    range: string
    required: true
    examples:
    - value: This mutation demonstrates that glutathionylation (in vivo oxidative
        post-translational modification of cysteine) of Mpro/NSP5 residue C300 is
        responsible for controlling the dimerization of the protein, where the monomer's
        protease activity is hampered by the collapsing  of the active site pocket.
  author:
    name: author
    title: author
    description: The last name of the first author of the paper or other resource
      containing the evidence for the mutation impact.
    comments: The surname of the publication's first author, without "et al." added.
    slot_uri: dcterms:creator
    range: string
    required: true
    examples:
    - value: Davis
  publication_year:
    name: publication_year
    title: publication year
    description: The publication year of the evidence source.
    slot_uri: dcterms:date
    range: integer
    required: true
    examples:
    - value: '2021'
  URL:
    name: URL
    title: URL
    description: A link to the literature evidence source.
    comments: If the evidence is found in supplemental material, still link to the
      paper itself.
    slot_uri: dcterms:source
    range: string
    required: true
    examples:
    - value: https://www.biorxiv.org/content/10.1101/2021.01.22.427749v1
  DOI:
    name: DOI
    title: DOI
    description: The DOI of the literature evidence source.
    slot_uri: dbXref
    range: string
    recommended: true
    examples:
    - value: 10.1101/2021.01.22.427749
  PMID:
    name: PMID
    title: PMID
    description: The PMID of the literature evidence source.
    slot_uri: dbXref
    range: string
    recommended: true
    examples:
    - value: '34755213'
  peer_review_status:
    name: peer_review_status
    title: peer review status
    description: 'Peer review status for the literature evidence document: true or
      false.'
    slot_uri: SIO:001035
    range: boolean
    required: true
    examples:
    - value: peer reviewed
  curator:
    name: curator
    title: curator
    description: The ORCID of the curator who created the annotation record.
    comments: If no ORCID is available, write the curator's full name here.
    slot_uri: dcterms:contributor
    range: string
    examples:
    - value: 0000-0002-0548-891X
  mutation_functional_annotation_resource:
    name: mutation_functional_annotation_resource
    title: mutation functional annotation resource
    description: The resource containing the functional annotation for the mutation.
    slot_uri: dcterms:seeAlso
    range: string
    examples:
    - value: Pokay, SARS-CoV-2 Harvest Variants
enums:
  organism menu:
    name: organism menu
    permissible_values:
      Severe acute respiratory syndrome coronavirus 2:
        text: Severe acute respiratory syndrome coronavirus 2
        meaning: NCBITaxon:2697049
  reference accession menu:
    name: reference accession menu
    permissible_values:
      NC_045512.2:
        text: NC_045512.2
  reference database menu:
    name: reference database menu
    permissible_values:
      RefSeq:
        text: RefSeq
  gene name menu:
    name: gene name menu
    permissible_values:
      open reading frame 1ab polyprotein gene (SARS-CoV-2):
        text: open reading frame 1ab polyprotein gene (SARS-CoV-2)
        meaning: GENEPIO:0101134
      open reading frame 1a polyprotein gene (SARS-CoV-2):
        text: open reading frame 1a polyprotein gene (SARS-CoV-2)
        meaning: GENEPIO:0101138
      surface glycoprotein gene (SARS-CoV-2):
        text: surface glycoprotein gene (SARS-CoV-2)
        meaning: GENEPIO:0101142
      open reading frame 3a gene (SARS-CoV-2):
        text: open reading frame 3a gene (SARS-CoV-2)
        meaning: GENEPIO:0101146
      envelope gene (SARS-CoV-2):
        text: envelope gene (SARS-CoV-2)
        meaning: GENEPIO:0101150
      membrane glycoprotein gene (SARS-CoV-2):
        text: membrane glycoprotein gene (SARS-CoV-2)
        meaning: GENEPIO:0101154
      open reading frame 6 gene (SARS-CoV-2):
        text: open reading frame 6 gene (SARS-CoV-2)
        meaning: GENEPIO:0101158
      open reading frame 7a gene (SARS-CoV-2):
        text: open reading frame 7a gene (SARS-CoV-2)
        meaning: GENEPIO:0101162
      open reading frame 7b gene (SARS-CoV-2):
        text: open reading frame 7b gene (SARS-CoV-2)
        meaning: GENEPIO:0101166
      open reading frame 8 gene (SARS-CoV-2):
        text: open reading frame 8 gene (SARS-CoV-2)
        meaning: GENEPIO:0101170
      nucleocapsid phosphoprotein gene (SARS-CoV-2):
        text: nucleocapsid phosphoprotein gene (SARS-CoV-2)
        meaning: GENEPIO:0101174
      open reading frame 10 gene (SARS-CoV-2):
        text: open reading frame 10 gene (SARS-CoV-2)
        meaning: GENEPIO:0101178
  gene symbol menu:
    name: gene symbol menu
    permissible_values:
      orf1ab gene (SARS-CoV-2):
        text: orf1ab gene (SARS-CoV-2)
        meaning: GENEPIO:0101135
      orf1a gene (SARS-CoV-2):
        text: orf1a gene (SARS-CoV-2)
        meaning: GENEPIO:0101139
      s gene (SARS-CoV-2):
        text: s gene (SARS-CoV-2)
        meaning: GENEPIO:0101143
      orf3a gene (SARS-CoV-2):
        text: orf3a gene (SARS-CoV-2)
        meaning: GENEPIO:0101147
      e gene (SARS-CoV-2):
        text: e gene (SARS-CoV-2)
        meaning: GENEPIO:0101151
      m gene (SARS-CoV-2):
        text: m gene (SARS-CoV-2)
        meaning: GENEPIO:0101155
      orf6 gene (SARS-CoV-2):
        text: orf6 gene (SARS-CoV-2)
        meaning: GENEPIO:0101159
      orf7a gene (SARS-CoV-2):
        text: orf7a gene (SARS-CoV-2)
        meaning: GENEPIO:0101163
      orf7b gene (SARS-CoV-2):
        text: orf7b gene (SARS-CoV-2)
        meaning: GENEPIO:0101167
      orf8 gene (SARS-CoV-2):
        text: orf8 gene (SARS-CoV-2)
        meaning: GENEPIO:0101171
      n gene (SARS-CoV-2):
        text: n gene (SARS-CoV-2)
        meaning: GENEPIO:0101175
      orf10 gene (SARS-CoV-2):
        text: orf10 gene (SARS-CoV-2)
        meaning: GENEPIO:0101179
  protein name menu:
    name: protein name menu
    permissible_values:
      open reading frame 1ab polyprotein (SARS-CoV-2):
        text: open reading frame 1ab polyprotein (SARS-CoV-2)
        meaning: GENEPIO:0101136
      open reading frame 1a polyprotein (SARS-CoV-2):
        text: open reading frame 1a polyprotein (SARS-CoV-2)
        meaning: GENEPIO:0101140
      surface glycoprotein (SARS-CoV-2):
        text: surface glycoprotein (SARS-CoV-2)
        meaning: GENEPIO:0101144
      open reading frame 3a protein (SARS-CoV-2):
        text: open reading frame 3a protein (SARS-CoV-2)
        meaning: GENEPIO:0101148
      envelope protein (SARS-CoV-2):
        text: envelope protein (SARS-CoV-2)
        meaning: GENEPIO:0101152
      membrane glycoprotein (SARS-CoV-2):
        text: membrane glycoprotein (SARS-CoV-2)
        meaning: GENEPIO:0101156
      open reading frame 6 protein (SARS-CoV-2):
        text: open reading frame 6 protein (SARS-CoV-2)
        meaning: GENEPIO:0101160
      open reading frame 7a protein (SARS-CoV-2):
        text: open reading frame 7a protein (SARS-CoV-2)
        meaning: GENEPIO:0101164
      open reading frame 7b protein (SARS-CoV-2):
        text: open reading frame 7b protein (SARS-CoV-2)
        meaning: GENEPIO:0101168
      open reading frame 8 protein (SARS-CoV-2):
        text: open reading frame 8 protein (SARS-CoV-2)
        meaning: GENEPIO:0101172
      nucleocapsid phosphoprotein (SARS-CoV-2):
        text: nucleocapsid phosphoprotein (SARS-CoV-2)
        meaning: GENEPIO:0101176
      open reading frame 10 protein (SARS-CoV-2):
        text: open reading frame 10 protein (SARS-CoV-2)
        meaning: GENEPIO:0101180
  protein symbol menu:
    name: protein symbol menu
    permissible_values:
      Orf1ab protein (SARS-CoV-2):
        text: Orf1ab protein (SARS-CoV-2)
        meaning: GENEPIO:0101137
      Orf1a protein (SARS-CoV-2):
        text: Orf1a protein (SARS-CoV-2)
        meaning: GENEPIO:0101141
      S protein (SARS-CoV-2):
        text: S protein (SARS-CoV-2)
        meaning: GENEPIO:0101145
      Orf3a protein (SARS-CoV-2):
        text: Orf3a protein (SARS-CoV-2)
        meaning: GENEPIO:0101149
      E protein (SARS-CoV-2):
        text: E protein (SARS-CoV-2)
        meaning: GENEPIO:0101153
      M protein (SARS-CoV-2):
        text: M protein (SARS-CoV-2)
        meaning: GENEPIO:0101157
      Orf6 protein (SARS-CoV-2):
        text: Orf6 protein (SARS-CoV-2)
        meaning: GENEPIO:0101161
      Orf7a protein (SARS-CoV-2):
        text: Orf7a protein (SARS-CoV-2)
        meaning: GENEPIO:0101165
      Orf7b protein (SARS-CoV-2):
        text: Orf7b protein (SARS-CoV-2)
        meaning: GENEPIO:0101169
      Orf8 protein (SARS-CoV-2):
        text: Orf8 protein (SARS-CoV-2)
        meaning: GENEPIO:0101173
      N protein (SARS-CoV-2):
        text: N protein (SARS-CoV-2)
        meaning: GENEPIO:0101177
      Orf10 protein (SARS-CoV-2):
        text: Orf10 protein (SARS-CoV-2)
        meaning: GENEPIO:0101181
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end,
      and all internal whitespace segments reduced to single spaces. Whitespace includes
      #x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
  Provenance:
    name: Provenance
    typeof: string
    description: A field containing a DataHarmonizer versioning marker. It is issued
      by DataHarmonizer when validation is applied to a given row of data.
    base: str
    uri: xsd:token
settings:
  Title_Case: (((?<=\b)[^a-z\W]\w*?|[\W])+)
  UPPER_CASE: '[A-Z\W\d_]*'
  lower_case: '[a-z\W\d_]*'
